# Copyright The PyTorch Lightning team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://docs.drone.io/pipeline/docker/examples/languages/python/#python-example

kind: pipeline
type: docker
name: torch-GPU

steps:
- name: testing
  image: pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.6

  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    AUTH_TOKEN:
      from_secret: gh_auth_token
    MKL_THREADING_LAYER: GNU

  commands:
    - python --version
    - pip --version
    - nvidia-smi
    - pip install -r ./requirements/devel.txt --upgrade-strategy only-if-needed -v --no-cache-dir
    - pip install git+https://${AUTH_TOKEN}@github.com/PyTorchLightning/lightning-dtrun.git@v0.0.2 -v --no-cache-dir
    # when Image has defined CUDa version we can switch to this package spec "nvidia-dali-cuda${CUDA_VERSION%%.*}0"
    # todo: temprarl fix till https://github.com/PyTorchLightning/pytorch-lightning/pull/4922 is resolved
    - pip install --extra-index-url https://developer.download.nvidia.com/compute/redist "nvidia-dali-cuda100<0.27" --upgrade-strategy only-if-needed
    - pip list
    - python -m coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=25 # --flake8
    # Running special tests
    - sh tests/special_tests.sh
    - coverage report
    - python -m pytest benchmarks pl_examples -v --maxfail=2 --durations=0
    # see: https://docs.codecov.io/docs/merging-reports
    - codecov --token $CODECOV_TOKEN --flags=gpu,pytest --name="GPU-coverage" --env=linux --build $DRONE_BUILD_NUMBER --commit $DRONE_COMMIT
    # --build $DRONE_BUILD_NUMBER --branch $DRONE_BRANCH --commit $DRONE_COMMIT --tag $DRONE_TAG --pr $DRONE_PULL_REQUEST
    # - codecov --token $CODECOV_TOKEN --flags=gpu,pytest --build $DRONE_BUILD_NUMBER
    - python tests/collect_env_details.py

trigger:
  branch:
    - master
    - release/*
  event:
    include:
    - push
    - pull_request
