# Copyright The PyTorch Lightning team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name:
    lightning

channels:
    - conda-forge
    - pytorch

dependencies:
    - python>=3.6
    - pip>20.1
    - numpy>=1.16.4
    - pytorch>=1.3,<1.8
    - future>=0.17.1
    - PyYAML>=5.1
    - tqdm>=4.41.0
    - fsspec>=0.8.0
    #- tensorboard>=2.2.0  # not needed, already included in pytorch

    # Optional
    #- nvidia-apex  # missing for py3.8
    - scikit-learn>=0.20.0
    - matplotlib>=3.1.1
    - omegaconf>=2.0.0
    - torchtext>=0.3.1

    # Examples
    - torchvision>=0.4.1,<0.9.0

    - pip:
        - test-tube>=0.7.5
        - mlflow>=1.0.0
        - comet_ml>=3.1.12
        - wandb>=0.8.21
        - neptune-client>=0.4.109
        - horovod>=0.19.2
        - onnxruntime>=1.3.0
        - gym>=0.17.0
